### ISSUE TITLE
const pointer and pointer to const.

### ISSUE THREAD

**Issue by Krym4s** [Masoudvahid/Dedinski#1]
See [https://github.com/Masoudvahid/Dedinski/blob/main/summer_2022/task_1_quadratic_equation/IO.cpp/#L3](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fgithub.com%2FMasoudvahid%2FDedinski%2Fblob%2Fmain%2Fsummer_2022%2Ftask_1_quadratic_equation%2FIO.cpp%2F%23L3) you can use const pointer parameters. Look for difference between ```const double * param``` and ``` double* const param```.

**Comment by Masoudvahid** [comment]
I have added the const in correct place and I get a warning from clang as following:
`Clang-Tidy: Parameter 'a' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions`
I think this warning is something to ignore, am I right?
